# Site settings
title: Dakota Cassidy
email: cococassidy@gmail.com
url: https://github.com/dakotacassidy.github.io
description: ""
keywords: "data analyst, machine learning, python, sql, r, excel"
skills: "Data Analysis - Python - SQL - R"
meta_author: Cassidy Dakota

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3E19A2 #80B3FF
  primary-rgb: "62,25,162" #"128,179,255"
  secondary: 633DCA #FD6E8A
  secondary-dark: 3E19A2 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/dakota-cassidy/
  - title: github
    url: http://github.com/dakotacassidy.github.io

# Postal address (add as many lines as necessary)
address:
  - line: Montclair, NJ, 07042

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
